### ISSUE TITLE
How to use view binding with this?

### ISSUE THREAD

**Issue by sarimmehdi** [nikartm/StripedProcessButton#1]
Cool library but I can't seem to have it work with view binding.

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.github.nikartm.support.StripedProcessButton
        android:id="@+id/droneActionButton"
        style="@style/droneActionsButton"
        android:background="@color/md_green"
        android:drawableLeft="@drawable/icon_nav_arrow_back"
        android:text="@string/item_drone_button_text"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```
The binding of the above layout does provide access to `droneActionButton` but I can't set the text on it.
`binding.droneActionButton.text = listItem.buttonText`
IDE says `Unresolved reference: text` but the above line works with a normal Button class

**Comment by nikartx** [comment]
Hi @sarimmehdi . It's a bug. I try to fix it in close future. Thanks for highlighting the issue.

**Comment by nikartx** [comment]
Hi @sarimmehdi. Try to use the new version of the library in Kotlin. Please change the dependencies as mentioned [here](https://github.com/nikartm/StripedProcessButton#after-migrating-to-mavencentral-use-groove). I added an example with view binding.

**Comment by nikartx** [comment]
If the issue persists, please open a new issue. I can't catch this error.
